name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCP_BUCKET_NAME: wodbooster
  TF_CLOUD_ORGANIZATION: jotadrilo
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_VAR_WB_USER_1: '"${{ secrets.TF_VAR_WB_USER_1 }}"'
  TF_VAR_WB_PASS_1: '"${{ secrets.TF_VAR_WB_PASS_1 }}"'
  TF_WORKSPACE: wodbooster
  TF_CONFIG_DIRECTORY: ./iac/deployment
  PACKER_CONFIG_DIRECTORY: ./iac/resources/image

jobs:
  packer:
    name: Run Packer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Configure Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: packer init ${{ env.PACKER_CONFIG_DIRECTORY }}/wodbooster.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: packer validate ${{ env.PACKER_CONFIG_DIRECTORY }}/wodbooster.pkr.hcl

      - name: Run `packer build`
        run: packer build -color=false -on-error=abort ${{ env.PACKER_CONFIG_DIRECTORY }}/wodbooster.pkr.hcl
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"

  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.TF_CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.4
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: Apply Run from GitHub Actions CI ${{ github.sha }}
